name: on pr terraform
on:
  pull_request:
    branches:
      - main
    paths:
      - 'class10/Terraform-advanced/**'
     



env:
  terraform_version: 1.13.3
  infra_path: class10/Terraform-advanced
  # infra_path: class8

jobs: 
  terraform-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Terraform install
        uses: hashicorp/setup-terraform@v3
        with:
            terraform_version: ${{ env.terraform_version }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Debug - Verify backend config file
        working-directory: ${{ env.infra_path }}
        run: |
          echo "=== Current Directory ==="
          pwd
          echo ""
          echo "=== Listing current directory ==="
          ls -la
          echo ""
          echo "=== Listing vars directory ==="
          ls -la vars/
          echo ""
          echo "=== Content of dev.tfbackend ==="
          cat vars/dev.tfbackend
          echo ""
          echo "=== Checking file exists ==="
          test -f vars/dev.tfbackend && echo "File EXISTS" || echo "File NOT FOUND"


      - name: Terraform Init
        working-directory: ${{ env.infra_path }}
        run: |
          terraform init -input=false \
            -backend-config="bucket=state-bucket-216989097838" \
            -backend-config="key=AugustBootie/dev/terraform.tfstate" \
            -backend-config="region=us-east-1" \
            -backend-config="encrypt=true"
        timeout-minutes: 5

      - name: Terraform fmt
        run: |
          cd ${{env.infra_path}} 
          terraform fmt -check

      - name: Terraform plan
        run: |
          cd ${{env.infra_path}} 
          terraform plan -var-file=vars/dev.tfvars

