name: terraform dev class12 destroy

on: 
  workflow_dispatch:

env:
  terraform_version: 1.13.3 
  infra_path: class10/Terraform-advanced

jobs:
  terraform-dev:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Terraform install
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.terraform_version }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform init
        working-directory: ${{ env.infra_path }}
        run: terraform init -backend-config=vars/dev.tfbackend
        timeout-minutes: 5

      - name: Terraform Apply
        working-directory: ${{ env.infra_path }}
        run: terraform destroy -var-file=vars/dev.tfvars --auto-approve
        timeout-minutes: 20